"""initial schema

Revision ID: 6fd55bac034c
Revises: 
Create Date: 2026-04-21 19:13:28.646667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd55bac034c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('bp_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('systolic_bp', sa.Float(), nullable=False),
    sa.Column('diastolic_bp', sa.Float(), nullable=False),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bp_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bp_records'))
    )
    with op.batch_alter_table('bp_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bp_records_user_id'), ['user_id'], unique=False)

    op.create_table('prophet_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('forecast_days', sa.Integer(), nullable=False),
    sa.Column('data_days_used', sa.Integer(), nullable=False),
    sa.Column('total_history_days', sa.Integer(), nullable=False),
    sa.Column('history_window_capped', sa.Boolean(), nullable=False),
    sa.Column('data_range', sa.String(length=100), nullable=True),
    sa.Column('cache_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prophet_predictions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prophet_predictions'))
    )
    with op.batch_alter_table('prophet_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prophet_predictions_cache_key'), ['cache_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_prophet_predictions_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('male', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('current_smoker', sa.Integer(), nullable=True),
    sa.Column('cigs_per_day', sa.Float(), nullable=True),
    sa.Column('bp_meds', sa.Integer(), nullable=True),
    sa.Column('diabetes', sa.Integer(), nullable=True),
    sa.Column('tot_chol', sa.Float(), nullable=True),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('diagnosis', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles'))
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('user_prophet_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('forecast_days', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('data_signature', sa.String(length=64), nullable=False),
    sa.Column('aggregation_mode', sa.String(length=32), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('trained_until', sa.Date(), nullable=False),
    sa.Column('data_days_used', sa.Integer(), nullable=False),
    sa.Column('total_history_days', sa.Integer(), nullable=False),
    sa.Column('history_window_capped', sa.Boolean(), nullable=False),
    sa.Column('parameter_profile', sa.String(length=32), nullable=False),
    sa.Column('weekly_enabled', sa.Boolean(), nullable=False),
    sa.Column('monthly_enabled', sa.Boolean(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_prophet_models_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_prophet_models'))
    )
    with op.batch_alter_table('user_prophet_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_prophet_models_data_signature'), ['data_signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_prophet_models_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_prophet_models_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_prophet_models_user_id'), ['user_id'], unique=False)

    op.create_table('prediction_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('prophet_prediction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prophet_prediction_id'], ['prophet_predictions.id'], name=op.f('fk_prediction_records_prophet_prediction_id_prophet_predictions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prediction_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_records'))
    )
    with op.batch_alter_table('prediction_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_records_user_id'), ['user_id'], unique=False)

    op.create_table('prediction_training_meta',
    sa.Column('prophet_prediction_id', sa.Integer(), nullable=False),
    sa.Column('aggregation_mode', sa.String(length=32), nullable=False),
    sa.Column('parameter_profile', sa.String(length=32), nullable=False),
    sa.Column('weekly_enabled', sa.Boolean(), nullable=False),
    sa.Column('monthly_enabled', sa.Boolean(), nullable=False),
    sa.Column('avg_measurements_per_day', sa.Float(), nullable=True),
    sa.Column('recent_sys_range_mean', sa.Float(), nullable=True),
    sa.Column('recent_dia_range_mean', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prophet_prediction_id'], ['prophet_predictions.id'], name=op.f('fk_prediction_training_meta_prophet_prediction_id_prophet_predictions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prophet_prediction_id', name=op.f('pk_prediction_training_meta'))
    )
    op.create_table('prophet_forecast_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prophet_prediction_id', sa.Integer(), nullable=False),
    sa.Column('forecast_day', sa.Integer(), nullable=False),
    sa.Column('systolic', sa.Float(), nullable=False),
    sa.Column('diastolic', sa.Float(), nullable=False),
    sa.Column('systolic_lower', sa.Float(), nullable=True),
    sa.Column('systolic_upper', sa.Float(), nullable=True),
    sa.Column('diastolic_lower', sa.Float(), nullable=True),
    sa.Column('diastolic_upper', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prophet_prediction_id'], ['prophet_predictions.id'], name=op.f('fk_prophet_forecast_points_prophet_prediction_id_prophet_predictions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prophet_forecast_points')),
    sa.UniqueConstraint('prophet_prediction_id', 'forecast_day', name='uq_prophet_forecast_points_prediction_day')
    )
    with op.batch_alter_table('prophet_forecast_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prophet_forecast_points_prophet_prediction_id'), ['prophet_prediction_id'], unique=False)

    op.create_table('prediction_confidence_reasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_record_id', sa.Integer(), nullable=False),
    sa.Column('reason_type', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_record_id'], ['prediction_records.id'], name=op.f('fk_prediction_confidence_reasons_prediction_record_id_prediction_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_confidence_reasons'))
    )
    with op.batch_alter_table('prediction_confidence_reasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_confidence_reasons_prediction_record_id'), ['prediction_record_id'], unique=False)

    op.create_table('prediction_fusion_meta',
    sa.Column('prediction_record_id', sa.Integer(), nullable=False),
    sa.Column('raw_probability', sa.Float(), nullable=False),
    sa.Column('fused_probability', sa.Float(), nullable=False),
    sa.Column('bp_meds_input', sa.Integer(), nullable=False),
    sa.Column('bp_meds_model_value', sa.Integer(), nullable=False),
    sa.Column('bp_meds_policy', sa.String(length=64), nullable=False),
    sa.Column('medication_adjustment', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_record_id'], ['prediction_records.id'], name=op.f('fk_prediction_fusion_meta_prediction_record_id_prediction_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_record_id', name=op.f('pk_prediction_fusion_meta'))
    )
    op.create_table('prediction_input_snapshots',
    sa.Column('prediction_record_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('male', sa.Integer(), nullable=False),
    sa.Column('current_smoker', sa.Integer(), nullable=False),
    sa.Column('cigs_per_day', sa.Float(), nullable=True),
    sa.Column('bp_meds', sa.Integer(), nullable=False),
    sa.Column('diabetes', sa.Integer(), nullable=False),
    sa.Column('tot_chol', sa.Float(), nullable=True),
    sa.Column('sys_bp', sa.Float(), nullable=False),
    sa.Column('dia_bp', sa.Float(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_record_id'], ['prediction_records.id'], name=op.f('fk_prediction_input_snapshots_prediction_record_id_prediction_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_record_id', name=op.f('pk_prediction_input_snapshots'))
    )
    op.create_table('prediction_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_record_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_record_id'], ['prediction_records.id'], name=op.f('fk_prediction_recommendations_prediction_record_id_prediction_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_recommendations'))
    )
    with op.batch_alter_table('prediction_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_recommendations_prediction_record_id'), ['prediction_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_recommendations_prediction_record_id'))

    op.drop_table('prediction_recommendations')
    op.drop_table('prediction_input_snapshots')
    op.drop_table('prediction_fusion_meta')
    with op.batch_alter_table('prediction_confidence_reasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_confidence_reasons_prediction_record_id'))

    op.drop_table('prediction_confidence_reasons')
    with op.batch_alter_table('prophet_forecast_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prophet_forecast_points_prophet_prediction_id'))

    op.drop_table('prophet_forecast_points')
    op.drop_table('prediction_training_meta')
    with op.batch_alter_table('prediction_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_records_user_id'))

    op.drop_table('prediction_records')
    with op.batch_alter_table('user_prophet_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_prophet_models_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_prophet_models_model_version'))
        batch_op.drop_index(batch_op.f('ix_user_prophet_models_is_active'))
        batch_op.drop_index(batch_op.f('ix_user_prophet_models_data_signature'))

    op.drop_table('user_prophet_models')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('prophet_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prophet_predictions_user_id'))
        batch_op.drop_index(batch_op.f('ix_prophet_predictions_cache_key'))

    op.drop_table('prophet_predictions')
    with op.batch_alter_table('bp_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bp_records_user_id'))

    op.drop_table('bp_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
