"""initial schema

Revision ID: 75f5fe8065f4
Revises: 
Create Date: 2026-05-10 23:41:02.629561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f5fe8065f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('bp_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('systolic_bp', sa.Float(), nullable=False),
    sa.Column('diastolic_bp', sa.Float(), nullable=False),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bp_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bp_records'))
    )
    with op.batch_alter_table('bp_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bp_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_bp_records_user_recorded_at', ['user_id', 'recorded_at'], unique=False)

    op.create_table('prediction_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('data_days_used', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.String(length=16), nullable=True),
    sa.Column('cache_mode', sa.String(length=32), nullable=False),
    sa.Column('has_anomaly', sa.Boolean(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('fusion_meta', sa.JSON(), nullable=True),
    sa.Column('bp_forecast', sa.JSON(), nullable=True),
    sa.Column('training_meta', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('anomaly_flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prediction_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_records'))
    )
    with op.batch_alter_table('prediction_records', schema=None) as batch_op:
        batch_op.create_index('ix_prediction_records_anomaly_created_at', ['has_anomaly', 'created_at'], unique=False)
        batch_op.create_index('ix_prediction_records_confidence_created_at', ['confidence_level', 'created_at'], unique=False)
        batch_op.create_index('ix_prediction_records_risk_created_at', ['risk_level', 'created_at'], unique=False)
        batch_op.create_index('ix_prediction_records_user_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_records_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles'))
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('user_prophet_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('data_signature', sa.String(length=64), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('trained_until', sa.Date(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_prophet_models_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_prophet_models'))
    )
    with op.batch_alter_table('user_prophet_models', schema=None) as batch_op:
        batch_op.create_index('ix_user_prophet_models_active_slot_trained', ['user_id', 'is_active', 'trained_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_prophet_models_user_id'), ['user_id'], unique=False)

    op.create_table('user_risk_factor_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('male', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('current_smoker', sa.Integer(), nullable=True),
    sa.Column('cigs_per_day', sa.Float(), nullable=True),
    sa.Column('bp_meds', sa.Integer(), nullable=True),
    sa.Column('diabetes', sa.Integer(), nullable=True),
    sa.Column('tot_chol', sa.Float(), nullable=True),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_risk_factor_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_risk_factor_profiles'))
    )
    with op.batch_alter_table('user_risk_factor_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_risk_factor_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_risk_factor_profiles')
    op.drop_table('user_prophet_models')
    op.drop_table('user_profiles')
    op.drop_table('prediction_records')
    op.drop_table('bp_records')
    op.drop_table('users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
